gupload: Show failed files or log it to a file | Fix #121
If upload failed for some files then

  If running in terminal, then

      if failed files > 20, then

        print to terminal

      else

        save to a log file, with a random name

  If not running in a terminal, then

      print all

diff --git a/sh/release/gupload b/sh/release/gupload
--- a/sh/release/gupload
+++ b/sh/release/gupload
@@ -855,7 +855,7 @@ _upload_file_main() {
         continue
     done
     [ -n "${4}" ] && {
-        { [ "${RETURN_STATUS}" = 1 ] && printf "%s\n" "${RETURN_STATUS}"; } || printf "%s\n" "${RETURN_STATUS}" 1>&2
+        { [ "${RETURN_STATUS}" = 1 ] && printf "%s\n" "${file_upload_file_main}"; } || printf "%s\n" "${file_upload_file_main}" 1>&2
     }
     return 0
 }
@@ -875,13 +875,15 @@ _upload_file_main() {
 _upload_folder() {
     [ $# -lt 3 ] && printf "Missing arguments\n" && return 1
     mode_upload_folder="${1}" PARSE_MODE="${2}" files_upload_folder="${3}" ID="${4:-}" && export PARSE_MODE ID
+    unset SUCCESS_STATUS SUCCESS_FILES ERROR_STATUS ERROR_FILES
     case "${mode_upload_folder}" in
         normal)
             [ "${PARSE_MODE}" = parse ] && _clear_line 1 && _newline "\n"
 
             while read -r file <&4; do
                 _upload_file_main "${PARSE_MODE}" "${file}" "${ID}"
-                : "$((RETURN_STATUS < 2 ? (SUCCESS_STATUS += 1) : (ERROR_STATUS += 1)))"
+                { [ "${RETURN_STATUS}" = 1 ] && : "$((SUCCESS_STATUS += 1))" && SUCCESS_FILES="$(printf "%b\n" "${SUCCESS_STATUS:+${SUCCESS_STATUS}\n}${file}")"; } ||
+                    { : "$((ERROR_STATUS += 1))" && ERROR_FILES="$(printf "%b\n" "${ERROR_STATUS:+${ERROR_STATUS}\n}${file}")"; }
                 if [ -n "${VERBOSE:-${VERBOSE_PROGRESS}}" ]; then
                     _print_center "justify" "Status: ${SUCCESS_STATUS} Uploaded" " | ${ERROR_STATUS} Failed" "=" && _newline "\n"
                 else
@@ -916,8 +918,9 @@ EOF
                     _clear_line 1 && "${QUIET:-_print_center}" "justify" "Status" ": ${SUCCESS_STATUS} Uploaded | ${ERROR_STATUS} Failed" "="
                 TOTAL="$((SUCCESS_STATUS + ERROR_STATUS))"
             done
-            SUCCESS_STATUS="$(($(wc -l < "${TMPFILE}"SUCCESS)))"
-            ERROR_STATUS="$(($(wc -l < "${TMPFILE}"ERROR)))"
+            SUCCESS_STATUS="$(($(wc -l < "${TMPFILE}"SUCCESS)))" SUCCESS_FILES="$(cat "${TMPFILE}"SUCCESS)"
+            ERROR_STATUS="$(($(wc -l < "${TMPFILE}"ERROR)))" ERROR_FILES="$(cat "${TMPFILE}"ERROR)"
+            export SUCCESS_FILES ERROR_FILES
             ;;
     esac
     return 0
@@ -1552,13 +1555,35 @@ EOF
             if [ "${EMPTY}" != 1 ]; then
                 [ -z "${VERBOSE:-${VERBOSE_PROGRESS}}" ] && for _ in 1 2; do _clear_line 1; done
 
-                [ "${SUCCESS_STATUS}" -gt 0 ] &&
-                    FOLDER_ID="$(_tmp="$(printf "%s\n" "${DIRIDS}" | while read -r line; do printf "%s\n" "${line}" && break; done)" && printf "%s\n" "${_tmp%%"|:_//_:|"*}")" &&
-                    _share_and_print_link "${FOLDER_ID}"
+                FOLDER_ID="$(_tmp="$(printf "%s\n" "${DIRIDS}" | while read -r line; do printf "%s\n" "${line}" && break; done)" && printf "%s\n" "${_tmp%%"|:_//_:|"*}")"
+
+                [ "${SUCCESS_STATUS}" -gt 0 ] && _share_and_print_link "${FOLDER_ID}"
 
                 _newline "\n"
                 [ "${SUCCESS_STATUS}" -gt 0 ] && "${QUIET:-_print_center}" "justify" "Total Files " "Uploaded: ${SUCCESS_STATUS}" "="
-                [ "${ERROR_STATUS}" -gt 0 ] && "${QUIET:-_print_center}" "justify" "Total Files " "Failed: ${ERROR_STATUS}" "="
+                [ "${ERROR_STATUS}" -gt 0 ] && "${QUIET:-_print_center}" "justify" "Total Files " "Failed: ${ERROR_STATUS}" "=" && {
+                    # If running inside a terminal, then check if failed files are more than 25, if not, then print, else save in a log file
+                    if [ -t 1 ]; then
+                        { [ "${ERROR_STATUS}" -le 25 ] && printf "%s\n" "${ERROR_FILES}"; } || {
+                            epoch_time="$(date +'%s')" log_file_name="${0##*/}_${FOLDER_NAME}_${epoch_time}.failed"
+                            # handle in case the vivid random file name was already there
+                            i=0 && until ! [ -f "${log_file_name}" ]; do
+                                : $((i += 1)) && log_file_name="${0##*/}_${FOLDER_NAME}_$((epoch_time + i)).failed"
+                            done
+                            printf "%s\n%s\n%s\n\n%s\n%s\n" \
+                                "Folder name: ${FOLDER_NAME} | Folder ID: ${FOLDER_ID}" \
+                                "Run this command to retry the failed uploads:" \
+                                "    ${0##*/} --skip-duplicates \"${input}\" --root-dir \"${NEXTROOTDIRID}\" ${SKIP_SUBDIRS:+-s} ${PARALLEL_UPLOAD:+--parallel} ${PARALLEL_UPLOAD:+${NO_OF_PARALLEL_JOBS}}" \
+                                "Failed files:" \
+                                "${ERROR_FILES}" >> "${log_file_name}"
+                            printf "%s\n" "To see the failed files, open \"${log_file_name}\""
+                            printf "%s\n" "To retry the failed uploads only, use -d / --skip-duplicates flag. See log file for more help."
+                        }
+                        # if not running inside a terminal, print it all
+                    else
+                        printf "%s\n" "${ERROR_FILES}"
+                    fi
+                }
                 printf "\n"
             else
                 for _ in 1 2 3; do _clear_line 1; done
