gupload: Add _cleanup_config function
this function removes any expired tokens on the basis of expiry

will be useful once service accounts or multi account config implemented

diff --git a/bash/release/gupload b/bash/release/gupload
--- a/bash/release/gupload
+++ b/bash/release/gupload
@@ -1062,6 +1062,35 @@ _version_info() {
 }
 
 ###################################################
+# Function to cleanup config file
+# Remove invalid access tokens on the basis of corresponding expiry
+# Globals: None
+# Arguments: 1
+#   ${1} = config file
+# Result: read description
+###################################################
+_cleanup_config() {
+    declare config="${1:?Error: Missing config}" values_regex
+
+    ! [ -f "${config}" ] && return 0
+
+    while read -r line; do
+        expiry_value_name="${line%%=*}"
+        token_value_name="${expiry_value_name%%_EXPIRY}"
+
+        : "${line##*=}" && : "${_%\"}" && expiry="${_#\"}"
+        [[ ${expiry} -le "$(printf "%(%s)T\\n" "-1")" ]] &&
+            values_regex="${values_regex:+${values_regex}|}${expiry_value_name}=\".*\"|${token_value_name}=\".*\""
+
+    done <<< "$(grep -F ACCESS_TOKEN_EXPIRY "${config}" || :)"
+
+    chmod +w "${config}" &&
+        printf "%s\n" "$(grep -Ev "^\$${values_regex:+|${values_regex}}" "${config}")" >| "${config}" &&
+        chmod -w "${config}"
+    return 0
+}
+
+###################################################
 # Process all arguments given to the script
 # Globals: 2 variable, 1 function
 #   Variable - HOME, CONFIG
@@ -1672,7 +1701,7 @@ main() {
                 printf "\n\n%s\n" "Script exited manually."
                 kill -- -$$ &
             else
-                _auto_update &
+                { _cleanup_config "${CONFIG}" && _auto_update; } &
             fi
         } 2>| /dev/null 1>&2 || :
         return 0
diff --git a/sh/release/gupload b/sh/release/gupload
--- a/sh/release/gupload
+++ b/sh/release/gupload
@@ -1048,6 +1048,36 @@ _version_info() {
 }
 
 ###################################################
+# Function to cleanup config file
+# Remove invalid access tokens on the basis of corresponding expiry
+# Globals: None
+# Arguments: 1
+#   ${1} = config file
+# Result: read description
+###################################################
+_cleanup_config() {
+    config="${1:?Error: Missing config}" && unset values_regex _tmp
+
+    ! [ -f "${config}" ] && return 0
+
+    while read -r line <&4; do
+        expiry_value_name="${line%%=*}"
+        token_value_name="${expiry_value_name%%_EXPIRY}"
+
+        _tmp="${line##*=}" && _tmp="${_tmp%\"}" && expiry="${_tmp#\"}"
+        [ "${expiry}" -le "$(date +"%s")" ] &&
+            values_regex="${values_regex:+${values_regex}|}${expiry_value_name}=\".*\"|${token_value_name}=\".*\""
+    done 4<< EOF
+$(grep -F ACCESS_TOKEN_EXPIRY "${config}" || :)
+EOF
+
+    chmod +w "${config}" &&
+        printf "%s\n" "$(grep -Ev "^\$${values_regex:+|${values_regex}}" "${config}")" >| "${config}" &&
+        chmod -w "${config}"
+    return 0
+}
+
+###################################################
 # Process all arguments given to the script
 # Globals: 1 variable, 1 function
 #   Variable - HOME
@@ -1682,7 +1712,7 @@ main() {
                 printf "\n\n%s\n" "Script exited manually."
                 kill -9 -$$ &
             else
-                _auto_update &
+                { _cleanup_config "${CONFIG}" && _auto_update; } &
             fi
         } 2>| /dev/null 1>&2 || :
         return 0
