gupload: More robust checking for credentials

diff --git a/bash/release/gupload b/bash/release/gupload
--- a/bash/release/gupload
+++ b/bash/release/gupload
@@ -398,7 +398,7 @@ _get_access_token_and_update() {
         _update_config ACCESS_TOKEN "${ACCESS_TOKEN}" "${CONFIG}"
         _update_config ACCESS_TOKEN_EXPIRY "$(($(printf "%(%s)T\\n" "-1") + $(_json_value expires_in 1 1 <<< "${RESPONSE}") - 1))" "${CONFIG}"
     else
-        "${QUIET:-_print_center}" "justify" "Error: Something went wrong" ", printing error." 1>&2
+        "${QUIET:-_print_center}" "justify" "Error: Something went wrong" ", printing error." "=" 1>&2
         printf "%s\n" "${RESPONSE}" 1>&2
         return 1
     fi
@@ -1249,34 +1249,75 @@ _check_credentials() {
         printf "%s\n" "Add in config manually if terminal is not accessible. CLIENT_ID, CLIENT_SECRET and REFRESH_TOKEN is required." && return 1
     }
 
-    until [[ -n ${CLIENT_ID} ]]; do
-        [[ -n ${client_id} ]] && for _ in 1 2 3; do _clear_line 1; done
-        printf "\n" && "${QUIET:-_print_center}" "normal" " Client ID " "-" && printf -- "-> "
+    until [[ -n ${CLIENT_ID} && -n ${CLIENT_ID_VALID} ]]; do
+        [[ -n ${CLIENT_ID} ]] && {
+            if [[ ${CLIENT_ID} =~ [0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com ]]; then
+                [[ -n ${client_id} ]] && _update_config CLIENT_ID "${CLIENT_ID}" "${CONFIG}"
+                CLIENT_ID_VALID="true" && continue
+            else
+                { [[ -n ${client_id} ]] && message="- Try again"; } || message="in config ( ${CONFIG} )"
+                "${QUIET:-_print_center}" "normal" " Invalid Client ID ${message} " "-" && unset CLIENT_ID client_id
+            fi
+        }
+        [[ -z ${client_id} ]] && printf "\n" && "${QUIET:-_print_center}" "normal" " Enter Client ID " "-"
+        [[ -n ${client_id} ]] && _clear_line 1
+        printf -- "-> "
         read -r CLIENT_ID && client_id=1
-    done && [[ -n ${client_id} ]] && _update_config CLIENT_ID "${CLIENT_ID}" "${CONFIG}"
+    done
 
-    until [[ -n ${CLIENT_SECRET} ]]; do
-        [[ -n ${client_secret} ]] && for _ in 1 2 3; do _clear_line 1; done
-        printf "\n" && "${QUIET:-_print_center}" "normal" " Client Secret " "-" && printf -- "-> "
+    until [[ -n ${CLIENT_SECRET} && -n ${CLIENT_SECRET_VALID} ]]; do
+        [[ -n ${CLIENT_SECRET} ]] && {
+            if [[ ${CLIENT_SECRET} =~ [0-9A-Za-z]{20,} ]]; then
+                [[ -n ${client_secret} ]] && _update_config CLIENT_SECRET "${CLIENT_SECRET}" "${CONFIG}"
+                CLIENT_SECRET_VALID="true" && continue
+            else
+                { [[ -n ${client_secret} ]] && message="- Try again"; } || message="in config ( ${CONFIG} )"
+                "${QUIET:-_print_center}" "normal" " Invalid Client Secret ${message} " "-" && unset CLIENT_SECRET client_secret
+            fi
+        }
+        [[ -z ${client_secret} ]] && printf "\n" && "${QUIET:-_print_center}" "normal" " Enter Client Secret " "-"
+        [[ -n ${client_secret} ]] && _clear_line 1
+        printf -- "-> "
         read -r CLIENT_SECRET && client_secret=1
-    done && [[ -n ${client_secret} ]] && _update_config CLIENT_SECRET "${CLIENT_SECRET}" "${CONFIG}"
+    done
 
     # Method to obtain refresh_token.
     # Requirements: client_id, client_secret and authorization code.
+    [[ -n ${REFRESH_TOKEN} ]] && {
+        ! [[ ${REFRESH_TOKEN} =~ 1//[0-9][0-9][0-9A-Za-z_]{26}-[0-9A-Za-z_]{50,} ]] &&
+            "${QUIET:-_print_center}" "normal" " Error: Invalid Refresh token in config file, follow below steps.. " "-" && unset REFRESH_TOKEN
+    }
+
     [[ -z ${REFRESH_TOKEN} ]] && {
         printf "\n" && "${QUIET:-_print_center}" "normal" "If you have a refresh token generated, then type the token, else leave blank and press return key.." " "
         printf "\n" && "${QUIET:-_print_center}" "normal" " Refresh Token " "-" && printf -- "-> "
         read -r REFRESH_TOKEN
         if [[ -n ${REFRESH_TOKEN} ]]; then
-            printf "\n\n" && _get_access_token_and_update && _update_config REFRESH_TOKEN "${REFRESH_TOKEN}" "${CONFIG}"
+            "${QUIET:-_print_center}" "normal" " Checking refresh token.. " "-"
+            if [[ "${REFRESH_TOKEN}" =~ 1//[0-9][0-9][0-9A-Za-z_]{26}-[0-9A-Za-z_]{50,} ]]; then
+                { _get_access_token_and_update && _update_config REFRESH_TOKEN "${REFRESH_TOKEN}" "${CONFIG}"; } || check_error=true
+            else
+                check_error=true
+            fi
+            [[ -n ${check_error} ]] && "${QUIET:-_print_center}" "normal" " Error: Invalid Refresh token given, follow below steps to generate.. " "-" && unset REFRESH_TOKEN
         else
-            for _ in 1 2; do _clear_line 1; done
-            "${QUIET:-_print_center}" "normal" "Visit the below URL, tap on allow and then enter the code obtained" " "
+            "${QUIET:-_print_center}" "normal" " No Refresh token given, follow below steps to generate.. " "-"
+        fi
+
+        [[ -z ${REFRESH_TOKEN} ]] && {
+            printf "\n" && "${QUIET:-_print_center}" "normal" "Visit the below URL, tap on allow and then enter the code obtained" " "
             URL="https://accounts.google.com/o/oauth2/auth?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URI}&scope=${SCOPE}&response_type=code&prompt=consent"
             printf "\n%s\n" "${URL}"
-            until [[ -n ${CODE} ]]; do
-                [[ -n ${code} ]] && for _ in 1 2 3; do _clear_line 1; done
-                printf "\n" && "${QUIET:-_print_center}" "normal" "Enter the authorization code" "-" && printf -- "-> "
+            until [[ -n ${CODE} && -n ${CODE_VALID} ]]; do
+                [[ -n ${CODE} ]] && {
+                    if [[ ${CODE} =~ [0-9A-Za-z]{20,} ]]; then
+                        CODE_VALID="true" && continue
+                    else
+                        "${QUIET:-_print_center}" "normal" " Invalid CODE given, try again.. " "-" && unset CODE code
+                    fi
+                }
+                { [[ -z ${code} ]] && printf "\n" && "${QUIET:-_print_center}" "normal" " Enter the authorization code " "-"; } || _clear_line 1
+                printf -- "-> "
                 read -r CODE && code=1
             done
             RESPONSE="$(curl --compressed "${CURL_PROGRESS_EXTRA}" -X POST \
@@ -1285,10 +1326,11 @@ _check_credentials() {
 
             REFRESH_TOKEN="$(_json_value refresh_token 1 1 <<< "${RESPONSE}" || :)"
             { _get_access_token_and_update "${RESPONSE}" && _update_config REFRESH_TOKEN "${REFRESH_TOKEN}" "${CONFIG}"; } || return 1
-        fi
+        }
     }
 
-    [[ -z ${ACCESS_TOKEN} || ${ACCESS_TOKEN_EXPIRY:-0} -lt "$(printf "%(%s)T\\n" "-1")" ]] && { _get_access_token_and_update || return 1; }
+    [[ -z ${ACCESS_TOKEN} || ! ${ACCESS_TOKEN} =~ ya29\.[0-9A-Za-z_-]+ || ${ACCESS_TOKEN_EXPIRY:-0} -lt "$(printf "%(%s)T\\n" "-1")" ]] &&
+        { _get_access_token_and_update || return 1; }
 
     # launch a background service to check access token and update it
     # checks ACCESS_TOKEN_EXPIRY, try to update before 5 mins of expiry, a fresh token gets 60 mins
